### ISSUE TITLE
Form aceita submissão com campo vazio

### ISSUE THREAD

**Issue by caike08** [marianadacunha/avocadoland-landing-page#2]
Prevenir que o formulário seja submetido sem o campo e-mail preenchido.
![image](https://user-images.githubusercontent.com/4422230/84189851-3b9a3680-aa96-11ea-98f9-b6e3c9339061.png)

**Bônus:** desabilitar o botão caso o valor não esteja preenchido.

**Comment by marianadacunha** [comment]
Feito!

![image](https://user-images.githubusercontent.com/53413113/84496419-39f68b80-acad-11ea-8f28-5b048b39f62f.png)
