### ISSUE TITLE
Elemento "Features" não centralizado

### ISSUE THREAD

**Issue by caike08** [marianadacunha/avocadoland-landing-page#3]
**Problema:** A seção "features" não está alinhada. Dessa forma, o elemento parece estar mais alinhado à direita.

**Atual:**
![image](https://user-images.githubusercontent.com/4422230/84190146-bc593280-aa96-11ea-8f27-341581a445b7.png)

**Esperado:**
![image](https://user-images.githubusercontent.com/4422230/84190289-fc201a00-aa96-11ea-9c65-03b37e64630a.png)

**Comment by marianadacunha** [comment]
Feito!

![image](https://user-images.githubusercontent.com/53413113/84496307-04ea3900-acad-11ea-9445-ef282492b5ce.png)
