### ISSUE TITLE
Ajustar título do card

### ISSUE THREAD

**Issue by caike08** [marianadacunha/avocadoland-landing-page#4]
Ajustar título do card, para que preencha melhor o espaço do card.

**Atualmente:**
![image](https://user-images.githubusercontent.com/4422230/84190499-54571c00-aa97-11ea-85df-7e75a59af346.png)

**Esperado:**
![image](https://user-images.githubusercontent.com/4422230/84190528-6042de00-aa97-11ea-8a25-073ad7558716.png)

**Comment by marianadacunha** [comment]
Feito!

![image](https://user-images.githubusercontent.com/53413113/84495385-601b2c00-acab-11ea-8e47-e529e3bcd2d9.png)
